services:
  financial-agent-api:
    build: .
    container_name: financial-agent-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    restart: unless-stopped
    networks:
      - financial-network

networks:
  financial-network:
    driver: bridge
